- name: Install dotnet from homebrew
  community.general.homebrew:
    name: dotnet
    state: present
    
- name: Rider IDE
  community.general.homebrew_cask:
    name: rider,jetbrains-toolbox
    state: present