# Configure shells and command-line tools
- import_tasks: tasks/zsh/main.yaml
- import_tasks: tasks/bash/main.yaml

# Install common applications
- import_tasks: tasks/applications/main.yaml

# Configure macOS
- import_tasks: tasks/osx/main.yaml