# Configure shells and command-line tools
- import_tasks: tasks/zsh/main.yaml
- import_tasks: tasks/bash/main.yaml

# Configure git
- import_tasks: tasks/git/main.yaml

# # Install common applications
# - import_tasks: tasks/applications/main.yaml

# Configure macOS
- import_tasks: tasks/macos/main.yaml
  when: ansible_facts['os_family'] == "Darwin"
