---
- name: Brew Packages
  hosts: macos
  

  tasks:
  - name: Development languages
    community.general.homebrew:
      name: golang,dotnet,antlr
      state: present

  - name: iTerm2
    community.general.homebrew_cask:
      name: iterm2
      state: present

  - name: Firefox
    community.general.homebrew_cask:
      name: firefox
      state: present

  - name: Zoom
    community.general.homebrew_cask:
      name: zoom
      state: present

  - name: 1Password
    community.general.homebrew_cask:
      name: 1password
      state: present

  - name: 1Password CLI
    community.general.homebrew_cask:
      name: 1password-cli
      state: present

  # - name: Go
  #   community.general.homebrew:
  #     name: golang
  #     state: present

  # - name: Dotnet
  #   community.general.homebrew:
  #     name: dotnet
  #     state: present

  - name: JetBrains Toolbox
    community.general.homebrew_cask:
      name: jetbrains-toolbox
      state: present

  - name: AnyDesk
    community.general.homebrew_cask:
      name: anydesk
      state: present

  - name: Postman
    community.general.homebrew_cask:
      name: postman
      state: present

  - name: Wireshark
    community.general.homebrew_cask:
      name: wireshark
      state: present

  - name: Goland
    community.general.homebrew_cask:
      name: goland
      state: present

  - name: Rider
    community.general.homebrew_cask:
      name: rider
      state: present

  - name: Visual Studio Code
    community.general.homebrew_cask:
      name: visual-studio-code
      state: present

  # - name: Antlr4
  #   community.general.homebrew:
  #     name: antlr
  #     state: present
