- name: Link zshrc configuration file to user profile
  ansible.builtin.file:
    src: "{{ role_path }}/files/zsh/zprofile"
    dest: ~/.zprofile
    state: link

- import_tasks: direnv/main.yaml
- import_tasks: fuzzyfinder/main.yaml
- import_tasks: oh-my-zsh/oh-my-zsh.yaml
- import_tasks: oh-my-zsh/powerlevel10k.yaml
