- name: Link zshrc configuration file to user profile
  ansible.builtin.file:
    src: "{{ role_path }}/files/zsh/zprofile"
    dest: ~/.zprofile
    state: link

- name: direnv
  import_tasks: direnv/main.yaml
- name: fuzzyfinder
  import_tasks: fuzzyfinder/main.yaml
- name: oh-my-zsh
  import_tasks: oh-my-zsh/oh-my-zsh.yaml
- name: powerlevel10k
  import_tasks: oh-my-zsh/powerlevel10k.yaml
