- name: Install 1password from homebrew
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - 1password
    - 1password-cli
  when: ansible_facts['os_family'] == "Darwin"

