- name: Install fuzzyfinder from homebrew
  community.general.homebrew:
    name: fzf
    state: present
  when: ansible_facts['os_family'] == "Darwin"


# - name: Enable bindings for fuzzyfinder
#   ansible.builtin.shell:
#     cmd: $(brew --prefix)/opt/fzf/install

- name: Link fuzzyfinder bash configuration to user profile
  ansible.builtin.file:
    src: "{{ role_path }}/files/zsh/fuzzyfinder/fzf.bash"
    dest: ~/.fzf.bash
    state: link

- name: Link fuzzyfinder zsh configuration to user profile
  ansible.builtin.file:
    src: "{{ role_path }}/files/zsh/fuzzyfinder/fzf.zsh"
    dest: ~/.fzf.zsh
    state: link