- name: Install 1password(-cli) from homebrew
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - 1password
    - 1password-cli

- name: Link ssh configuration file to user profile
  ansible.builtin.file:
    src: "{{ role_path }}/files/ssh/config"
    dest: ~/.ssh/config
    state: link
    force: true
